[glowbot]
log_level = "DEBUG"

[discord]
discord_token = "DISCORD_TOKEN"
discord_cogs = [
    'ping',
]

[database]
database_url = "localhost/glowbot"
database_name = "glowbot"
database_user = "glowbot"
database_password = "glowbot"