[tool.poetry]
name = "glowbot"
version = "0.1.0"
description = "Glow's Hell Let Loose Discord Bot"
authors = ["Robb Manes <robbmanes@protonmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
tomli = "^2.0.1"
asyncpg = "^0.27.0"
py-cord = "^2.4.0"
tortoise-orm = {extras = ["asyncpg"], version = "^0.19.3"}
aiohttp = "^3.8.4"
aerich = "^0.7.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
sphinx = "^6.1.3"
myst-parser = "^1.0.0"
furo = "^2023.3.27"

[tool.poetry.scripts]
glowbot-discord = "glowbot.main:run_discord_bot"
glowbot-gameservice = "glowbot.main:run_hll_gameservice"

[build-system]
requires = [
    "poetry-core>=1.0.0",
]
build-backend = "poetry.core.masonry.api"
