[tool.poetry]
name = "fishbot"
version = "0.1.0"
description = "Fishy Community Discord Bot"
authors = ["Robb Manes <robbmanes@protonmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
tomli = "^2.0.1"
asyncpg = "^0.27.0"
py-cord = "^2.4.0"
tortoise-orm = {extras = ["asyncpg"], version = "^0.19.3"}
aiohttp = "^3.8.4"
aerich = "^0.7.1"
APScheduler = "^3.10.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
fishbot-discord = "fishbot.discord_bot:run_discord_bot"

[build-system]
requires = [
    "poetry-core>=1.0.0",
]
build-backend = "poetry.core.masonry.api"
